name: Build and Push Docker Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        java-version: [17]
        project: [java-compressor]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Java Compressor
        uses: docker/build-push-action@v5
        with:
          context: ./java-compressor
          file: ./java-compressor/Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: ghcr.io/guy-ghis/java-compressor:latest